"use client";
import Link from "next/link";
import { useEffect,useMemo,useRef,useState } from "react";
import { Bookmark,Check,Command,Search,Share2 } from "lucide-react";
import { companies,getIntelligence } from "@/lib/companies";
import { CompanyMark,OrbitFooter,OrbitHeader } from "@/components/company-ui";

const modules=["New","Tools","Agents","Tasks","Companies","News","Videos","Robots","Devices","Models","Repositories","MCP","Personal"];
const categories=["All","AI Model Providers","Infrastructure","Enterprise","Healthcare","Generative AI","Marketing","Developer Tools","Robotics","Education","Open Source","Finance","AI Native","Model Companies","Unicorns"];
const trends=["Trending","Popular","New","Free","Top Rated"];
const stats:Record<string,{valuation:string;native:boolean;profitable:boolean;sector:string;models:number;tools:number}>={
openai:{valuation:"$300B",native:true,profitable:false,sector:"Generative AI",models:9,tools:7},anthropic:{valuation:"$61.5B",native:true,profitable:false,sector:"AI Model Providers",models:8,tools:4},"mistral-ai":{valuation:"$14B",native:true,profitable:false,sector:"AI Model Providers",models:12,tools:3},perplexity:{valuation:"$18B",native:true,profitable:false,sector:"AI Search",models:0,tools:3},elevenlabs:{valuation:"$6.6B",native:true,profitable:false,sector:"Voice & Audio",models:5,tools:7},runway:{valuation:"$5.3B",native:true,profitable:false,sector:"Generative AI",models:7,tools:5},cohere:{valuation:"$5.5B",native:true,profitable:false,sector:"Enterprise",models:9,tools:4},"hugging-face":{valuation:"$4.5B",native:true,profitable:true,sector:"Developer Tools",models:99,tools:8},"scale-ai":{valuation:"$29B",native:true,profitable:true,sector:"Infrastructure",models:0,tools:6},synthesia:{valuation:"$4B",native:true,profitable:false,sector:"Generative AI",models:3,tools:5},groq:{valuation:"$6.9B",native:true,profitable:false,sector:"Infrastructure",models:0,tools:4},suno:{valuation:"$2.5B",native:true,profitable:false,sector:"Voice & Audio",models:4,tools:2}};

export default function Home(){
const[query,setQuery]=useState("");const[category,setCategory]=useState("All");const[sort,setSort]=useState("Newest");const[saved,setSaved]=useState<string[]>([]);const[trend,setTrend]=useState("");const[page,setPage]=useState(1);const[toast,setToast]=useState("");const searchRef=useRef<HTMLInputElement>(null);const pageSize=8;
useEffect(()=>{const timer=window.setTimeout(()=>{try{setSaved(JSON.parse(localStorage.getItem("orbit-company-bookmarks")||"[]"));}catch{}},0);return()=>window.clearTimeout(timer);},[]);
useEffect(()=>{const timer=window.setTimeout(()=>{const view=new URLSearchParams(window.location.search).get("view");if(view==="business"){setCategory("Enterprise");setTrend("")}if(view==="top"){setCategory("All");setTrend("Top Rated")}},0);return()=>window.clearTimeout(timer)},[]);
useEffect(()=>{function shortcut(event:KeyboardEvent){if((event.metaKey||event.ctrlKey)&&event.key.toLowerCase()==="k"){event.preventDefault();searchRef.current?.focus();}}window.addEventListener("keydown",shortcut);return()=>window.removeEventListener("keydown",shortcut)},[]);
const filtered=useMemo(()=>companies.filter(c=>{const q=query.toLowerCase(),s=stats[c.slug];return(!q||`${c.name} ${c.description} ${c.products.join(" ")}`.toLowerCase().includes(q))&&(category==="All"||category===s.sector||category===c.category||(category==="AI Native"&&s.native));}).sort((a,b)=>trend==="Trending"?getIntelligence(b.slug).momentum-getIntelligence(a.slug).momentum:trend==="Popular"||trend==="Top Rated"?b.score-a.score:sort==="A–Z"?a.name.localeCompare(b.name):sort==="Valuation"?Number(stats[b.slug].valuation.replace(/[^0-9.]/g,""))-Number(stats[a.slug].valuation.replace(/[^0-9.]/g,"")):b.founded-a.founded),[query,category,sort,trend]);
const pages=Math.max(1,Math.ceil(filtered.length/pageSize));const visible=filtered.slice((page-1)*pageSize,page*pageSize);
function toggle(slug:string){setSaved(current=>{const next=current.includes(slug)?current.filter(x=>x!==slug):[...current,slug];localStorage.setItem("orbit-company-bookmarks",JSON.stringify(next));return next;});}
async function share(name:string,slug:string){const url=`${location.origin}/companies/${slug}`;try{if(navigator.share)await navigator.share({title:name,url});else{await navigator.clipboard.writeText(url);setToast("Company link copied");window.setTimeout(()=>setToast(""),1800)}}catch{}}
function selectTrend(value:string){setTrend(current=>current===value?"":value);setPage(1)}
function unavailableModule(value:string){setToast(`${value} is outside the Companies module`);window.setTimeout(()=>setToast(""),1800)}
function jumpTo(id:string){window.setTimeout(()=>document.getElementById(id)?.scrollIntoView({behavior:"smooth",block:"start"}),0)}
function showBusiness(){setCategory("Enterprise");setTrend("");setPage(1);jumpTo("directory")}
function showLeaderboard(){setCategory("All");setTrend("Top Rated");setPage(1);jumpTo("directory")}
return <div className="reference-home"><OrbitHeader onBusiness={showBusiness} onLeaderboard={showLeaderboard} onResources={()=>jumpTo("directory")} onNewsletter={()=>jumpTo("newsletter")}/><section className="orbit-hero"><h1>The Home of Everything AI</h1><label className="orbit-global-search"><Search size={17}/><input ref={searchRef} value={query} onChange={e=>{setQuery(e.target.value);setPage(1)}} placeholder="Search AI tools, models, companies..."/><span><Command size={12}/> K</span></label><div className="orbit-trends">{trends.map(x=><button key={x} className={trend===x?"active":""} onClick={()=>selectTrend(x)}>{x}</button>)}</div></section>
<main className="orbit-directory-main" id="directory"><div className="orbit-sort"><span>Sort by</span><select value={sort} onChange={e=>{setSort(e.target.value);setTrend("");setPage(1)}}><option>Newest</option><option>Valuation</option><option>A–Z</option></select></div><nav className="orbit-module-rail">{modules.map(x=>x==="Companies"?<Link key={x} className="active" href="/"><i>{x.slice(0,1)}</i>{x}</Link>:<button type="button" key={x} onClick={()=>unavailableModule(x)}><i>{x.slice(0,1)}</i>{x}</button>)}</nav><div className="orbit-category-rail">{categories.map(x=><button key={x} className={category===x?"active":""} onClick={()=>{setCategory(x);setPage(1)}}>{x}</button>)}</div>
<div className="orbit-table-wrap"><div className="orbit-company-table" role="table"><div className="orbit-table-head" role="row"><span>COMPANY ↕</span><span>COUNTRY</span><span>VALUATION ↓</span><span>VAL/EMP ↕</span><span>AI NATIVE ↕</span><span>PROFITABLE ↕</span><span>SECTOR ↕</span><span>MODELS ↕</span><span>TOOLS ↕</span><span>SHARE</span><span>BOOKMARK</span></div>{visible.map(company=>{const s=stats[company.slug],intel=getIntelligence(company.slug);return <div className="orbit-company-row" role="row" key={company.slug}><Link className="orbit-company-cell" href={`/companies/${company.slug}`}><CompanyMark company={company}/><span><strong>{company.name}{company.verified&&<b><Check size={9}/></b>}</strong><small>{company.products.slice(0,2).map(p=><em key={p}>{p}</em>)}</small></span></Link><span>{company.location}</span><strong>{s.valuation}</strong><span>{intel.funding}</span><span className="yes"><Check size={10}/> YES</span><span className={s.profitable?"yes":"no"}>{s.profitable?<><Check size={10}/> YES</>:"NO"}</span><span>{s.sector}</span><strong>{s.models}</strong><strong>{s.tools}</strong><button className="orbit-round-action" onClick={()=>share(company.name,company.slug)} aria-label={`Share ${company.name}`}><Share2 size={14}/></button><button className={`orbit-round-action ${saved.includes(company.slug)?"saved":""}`} onClick={()=>toggle(company.slug)} aria-label={`Bookmark ${company.name}`}><Bookmark size={14} fill={saved.includes(company.slug)?"currentColor":"none"}/></button></div>})}</div></div>
{!filtered.length&&<div className="orbit-empty"><Search/><h2>No companies found</h2><button onClick={()=>{setQuery("");setCategory("All")}}>Clear filters</button></div>}<div className="orbit-pagination"><span>Showing {filtered.length?(page-1)*pageSize+1:0}–{Math.min(page*pageSize,filtered.length)} of {filtered.length} companies</span><div><button disabled={page===1} onClick={()=>setPage(x=>Math.max(1,x-1))}>‹</button>{Array.from({length:pages},(_,i)=>i+1).map(number=><button key={number} className={page===number?"active":""} onClick={()=>setPage(number)}>{number}</button>)}<button disabled={page===pages} onClick={()=>setPage(x=>Math.min(pages,x+1))}>›</button></div></div></main>{toast&&<div className="orbit-toast">{toast}</div>}<OrbitFooter/></div>;
}
