export type Company = {
  id: number; name: string; slug: string; initials: string; shortDescription: string;
  description: string; category: string; stage: string; location: string;
  headquarters: string; founded: number; employees: string; website: string;
  featured: boolean; verified: boolean; score: number; color: string;
  products: string[]; focus: string[];
};

export const companies: Company[] = [
  { id: 1, name: "Anthropic", slug: "anthropic", initials: "A", category: "Foundation Models", stage: "Growth", location: "United States", headquarters: "San Francisco, CA", founded: 2021, employees: "1,000+", website: "anthropic.com", featured: true, verified: true, score: 98, color: "#d97757", shortDescription: "AI safety and research company building reliable, interpretable AI systems.", description: "Anthropic is an AI safety and research company working to build reliable, interpretable, and steerable AI systems. Its interdisciplinary team develops frontier models for individuals and businesses.", products: ["Claude", "Claude API", "Claude for Enterprise"], focus: ["AI Safety", "Large Language Models", "Enterprise AI"] },
  { id: 2, name: "OpenAI", slug: "openai", initials: "O", category: "Foundation Models", stage: "Growth", location: "United States", headquarters: "San Francisco, CA", founded: 2015, employees: "5,000+", website: "openai.com", featured: true, verified: true, score: 100, color: "#7dd3b0", shortDescription: "AI research and deployment company advancing broadly useful intelligence.", description: "OpenAI is an AI research and deployment company. Its work spans multimodal foundation models, developer platforms, and products that help people use advanced AI in everyday work.", products: ["ChatGPT", "OpenAI API", "Codex"], focus: ["Generative AI", "Multimodal Models", "Developer Tools"] },
  { id: 3, name: "Mistral AI", slug: "mistral-ai", initials: "M", category: "Foundation Models", stage: "Scale-up", location: "France", headquarters: "Paris, France", founded: 2023, employees: "250+", website: "mistral.ai", featured: true, verified: true, score: 94, color: "#ff8a3d", shortDescription: "Frontier AI lab delivering efficient open and commercial language models.", description: "Mistral AI develops efficient frontier models and AI products with an emphasis on openness, portability, and enterprise deployment.", products: ["Le Chat", "La Plateforme", "Mistral Models"], focus: ["Open Models", "Enterprise AI", "Model Efficiency"] },
  { id: 4, name: "Perplexity", slug: "perplexity", initials: "P", category: "AI Search", stage: "Growth", location: "United States", headquarters: "San Francisco, CA", founded: 2022, employees: "500+", website: "perplexity.ai", featured: true, verified: true, score: 96, color: "#4fd1c5", shortDescription: "Answer engine turning web research into clear, cited responses.", description: "Perplexity builds an AI-powered answer engine designed to help people explore information, research topics, and understand sources quickly.", products: ["Perplexity", "Perplexity Pro", "Enterprise Pro"], focus: ["AI Search", "Research", "Knowledge Discovery"] },
  { id: 5, name: "ElevenLabs", slug: "elevenlabs", initials: "E", category: "Voice & Audio", stage: "Growth", location: "United Kingdom", headquarters: "London, UK", founded: 2022, employees: "500+", website: "elevenlabs.io", featured: true, verified: true, score: 93, color: "#a78bfa", shortDescription: "Voice AI platform for natural speech, dubbing, and audio experiences.", description: "ElevenLabs develops voice technology for creators, developers, and enterprises, covering speech synthesis, localization, dubbing, and conversational audio.", products: ["Text to Speech", "Voice Library", "Conversational AI"], focus: ["Speech Synthesis", "Audio", "Localization"] },
  { id: 6, name: "Runway", slug: "runway", initials: "R", category: "Video Generation", stage: "Growth", location: "United States", headquarters: "New York, NY", founded: 2018, employees: "500+", website: "runwayml.com", featured: false, verified: true, score: 91, color: "#6ea8fe", shortDescription: "Applied AI research company building tools for human creativity.", description: "Runway is an applied AI research company creating multimodal systems and filmmaking tools for artists, studios, and creative teams.", products: ["Runway", "Gen Models", "Runway Studios"], focus: ["Video Generation", "Creative Tools", "Multimodal AI"] },
  { id: 7, name: "Cohere", slug: "cohere", initials: "C", category: "Enterprise AI", stage: "Growth", location: "Canada", headquarters: "Toronto, Canada", founded: 2019, employees: "1,000+", website: "cohere.com", featured: false, verified: true, score: 89, color: "#d8b4fe", shortDescription: "Secure language models and retrieval systems built for business.", description: "Cohere builds secure enterprise AI systems, including language models, retrieval, and workplace products designed for private business data.", products: ["Command", "Embed", "North"], focus: ["Enterprise AI", "Retrieval", "Private Deployment"] },
  { id: 8, name: "Hugging Face", slug: "hugging-face", initials: "HF", category: "Developer Tools", stage: "Growth", location: "United States", headquarters: "New York, NY", founded: 2016, employees: "500+", website: "huggingface.co", featured: false, verified: true, score: 95, color: "#ffd84d", shortDescription: "Open platform where the machine learning community builds and shares.", description: "Hugging Face provides an open collaboration platform for machine learning models, datasets, applications, and developer tooling.", products: ["Model Hub", "Datasets", "Spaces"], focus: ["Open Source", "Machine Learning", "Developer Platform"] },
  { id: 9, name: "Scale AI", slug: "scale-ai", initials: "S", category: "Data Infrastructure", stage: "Mature", location: "United States", headquarters: "San Francisco, CA", founded: 2016, employees: "1,000+", website: "scale.com", featured: false, verified: true, score: 88, color: "#86efac", shortDescription: "Data infrastructure and evaluation systems for advanced AI.", description: "Scale AI provides data infrastructure, evaluation, and application tooling to accelerate the development and deployment of AI systems.", products: ["Scale Data Engine", "Scale GenAI Platform", "Scale Evaluation"], focus: ["Training Data", "Model Evaluation", "Infrastructure"] },
  { id: 10, name: "Synthesia", slug: "synthesia", initials: "S", category: "Video Generation", stage: "Growth", location: "United Kingdom", headquarters: "London, UK", founded: 2017, employees: "500+", website: "synthesia.io", featured: false, verified: true, score: 87, color: "#f472b6", shortDescription: "Enterprise AI video platform for scalable business communication.", description: "Synthesia helps organizations create and localize professional video using AI avatars, voice, and collaborative production tools.", products: ["AI Video Generator", "AI Avatars", "Video Localization"], focus: ["Enterprise Video", "Avatars", "Learning & Development"] },
  { id: 11, name: "Groq", slug: "groq", initials: "G", category: "AI Infrastructure", stage: "Scale-up", location: "United States", headquarters: "Mountain View, CA", founded: 2016, employees: "500+", website: "groq.com", featured: false, verified: true, score: 90, color: "#f59e0b", shortDescription: "Fast AI inference infrastructure powered by purpose-built compute.", description: "Groq develops purpose-built compute and cloud infrastructure focused on predictable, low-latency inference for AI applications.", products: ["GroqCloud", "LPU Inference Engine", "Groq API"], focus: ["AI Inference", "Compute", "Developer Infrastructure"] },
  { id: 12, name: "Suno", slug: "suno", initials: "S", category: "Voice & Audio", stage: "Scale-up", location: "United States", headquarters: "Cambridge, MA", founded: 2022, employees: "100+", website: "suno.com", featured: false, verified: true, score: 86, color: "#fb7185", shortDescription: "Generative music platform that turns ideas into complete songs.", description: "Suno creates generative music technology that enables people to make original songs from simple creative prompts.", products: ["Suno Music", "Suno Studio"], focus: ["Music Generation", "Creative AI", "Audio"] }
];

export const categories = ["All categories", ...Array.from(new Set(companies.map((company) => company.category)))];
export const stages = ["All stages", ...Array.from(new Set(companies.map((company) => company.stage)))];
export const getCompany = (slug: string) => companies.find((company) => company.slug === slug);
